### ISSUE TITLE
SocialLink to Twitter not working

### ISSUE THREAD

**Issue by edisim** [ivoberger/ivoberger.com#256]
https://github.com/ivoberger/ivoberger.com/blob/10f0d21f7d6c080098ab76e6a5b558b33d31a83e/src/lib/components/Footer/Footer.svelte#L38

The referenced URL leads to a non-existent Twitter account.

**Comment by ivoberger** [comment]
right, I deleted that 😅
Thanks for heads up, I removed it now.
